// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: notifier_v1/notifier.proto

package notifier_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NotifierRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *NotifierRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NotifierRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NotifierRequestMultiError, or nil if none found.
func (m *NotifierRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *NotifierRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Phone

	// no validation rules for Text

	if len(errors) > 0 {
		return NotifierRequestMultiError(errors)
	}

	return nil
}

// NotifierRequestMultiError is an error wrapping multiple validation errors
// returned by NotifierRequest.ValidateAll() if the designated constraints
// aren't met.
type NotifierRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NotifierRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NotifierRequestMultiError) AllErrors() []error { return m }

// NotifierRequestValidationError is the validation error returned by
// NotifierRequest.Validate if the designated constraints aren't met.
type NotifierRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NotifierRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NotifierRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NotifierRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NotifierRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NotifierRequestValidationError) ErrorName() string { return "NotifierRequestValidationError" }

// Error satisfies the builtin error interface
func (e NotifierRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotifierRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NotifierRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NotifierRequestValidationError{}

// Validate checks the field values on NotifierResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *NotifierResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NotifierResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NotifierResponseMultiError, or nil if none found.
func (m *NotifierResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NotifierResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return NotifierResponseMultiError(errors)
	}

	return nil
}

// NotifierResponseMultiError is an error wrapping multiple validation errors
// returned by NotifierResponse.ValidateAll() if the designated constraints
// aren't met.
type NotifierResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NotifierResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NotifierResponseMultiError) AllErrors() []error { return m }

// NotifierResponseValidationError is the validation error returned by
// NotifierResponse.Validate if the designated constraints aren't met.
type NotifierResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NotifierResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NotifierResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NotifierResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NotifierResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NotifierResponseValidationError) ErrorName() string { return "NotifierResponseValidationError" }

// Error satisfies the builtin error interface
func (e NotifierResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotifierResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NotifierResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NotifierResponseValidationError{}
